### PR TITLE
Add Dynatrace Query langage 

### PR DESCRIPTION
**Pull request by henrikrexed**
Describing the Dynatrace Query Langage and adding few examples on how to query :
- traces
- metrics

### CODE REVIEW

**Comment by alolita** [comment]
@manolama can you review too?

**Review by manolama — APPROVED** [review]

**Comment by manolama** [comment]
@alolita Done but it looks like I still don't have write access so it doesn't consider the my approval acceptable.

**Comment by alolita** [comment]
Thanks for reviewing @manolama

**Review by alolita — APPROVED** [review]
LGTM.

**Review by bwplotka — APPROVED** [review]
👍🏽 

Do you mind fixing DOC bot @henrikrexed ?

**Comment by manolama** [comment]
We could also squash merge to clear up the DCO check. Some are signed.

**Comment by alolita** [comment]
@henrikrexed please sign the DCO so that we can merge the PR.

**Review by vjsamuel — APPROVED** [review]

**Pull request merged**
