### PR TITLE
Few whitepaper typo corrections

### PR DESCRIPTION
**Pull request by rverchere**
Some corrections while reviewing #51 :

* Capitals
* Logs list
* ObservatoRium

### CODE REVIEW

**Comment by ArthurSens** [comment]
Hey @rverchere thanks for the PR!

Do you mind opening it against my fork? https://github.com/ArthurSens/sig-observability/tree/public-review

Since I'm not a member of CNCF's org I'm not able to merge your review 😬. After your PR against my fork is merged, the commit will added to #51 :)

**Comment by rverchere** [comment]
> Do you mind opening it against my fork? https://github.com/ArthurSens/sig-observability/tree/public-review
> 
Done!

**Comment by ArthurSens** [comment]
It was merged against my fork, could we close this one then? 🙂

**Comment by rverchere** [comment]
Sure!

**Pull request closed without merging**
