### PR TITLE
Query WG: Add extraction group questions for regex.

### PR DESCRIPTION
**Pull request by manolama**
Re: https://cloud-native.slack.com/archives/C057ZDS60PP/p1686722230931049

### CODE REVIEW

**Review by bwplotka — APPROVED** [review]
👍🏽

**Comment by bwplotka** [comment]
Are etraction groups defined anywhere in the doc? (:

**Comment by manolama** [comment]
Thanks! I didn't have an explicit definition anywhere so I updated the question to clarify a bit. Let me know that works please.

**Review by alolita — APPROVED** [review]
Lgtm

**Pull request merged**
